### PR TITLE
Adds elm-review --fix code generators for generating 'Optional's for …

### PR DESCRIPTION
**Pull request by erlandsona**
…Constructors of a Sum type.

### CODE REVIEW

**Comment by Janiczek** [comment]
Should this additional rule live under this package name? It might be a bit unfindable? (Unless the repo becomes a go-to for codegen rules 😁 )

**Comment by lue-bird** [comment]
@Janiczek Sorry, we only discussed this privately:
The final solution is me publishing generate-elm with everything you could want (field helper functions, lenses, prisms, conversions, svg, html, ... lots of stuff) regarding code-gen

This PR which I'll merge into record-field-lens is only supposed to be a temporary solution to not pollute packages.

**Comment by lue-bird** [comment]
Ah... and as you see, I'll have to do some clean-up, restoring the package state to what was last published as it seems like I've made some breaking changes that were pushed before I started elm-generate :shrug:

**Comment by erlandsona** [comment]
@lue-bird 
> (if anyone is willing to do it before me, go ahead 👀)
Just pushed an update, not sure that was the only thing but should work?

**Comment by lue-bird** [comment]
There are still a couple of things, names of tests etc. different.. Working from the previous published tagged version would I help I assume

**Comment by lue-bird** [comment]
There also seem to be some errors in your files:
- test `CheckPrismsWork` uses `makeOneToN`but imports `makeOneToN_`

**Comment by lue-bird** [comment]
names:
- constructors → variants?
- custom types → `type` unions / variant types?

**Comment by erlandsona** [comment]
@lue-bird 
> names:
> 
> * constructors → variants?
> * custom types → `type` unions / variant types?

Not a fan of Variant coming from ReasonML... it's not necessarily clearer just cause it's different... also variant is the description of a type not it's constructors. In Reason you'd still have a "Variant Type w/ Constructors" 🤷‍♂️ 

Elm people usually refer to Sum types as "Custom Types" in my experience. But the pattern has so many synonyms I think we're screwed no matter where we end up.

Also Elm has `tagged union`'s not `unions` (aka: structural typing) which would be `type IntyString = String | Int` which is not expressible in Elm.
In TS to get proper tagged unions (aka: nominal typing) like you have to 
```ts
type NominalThingy<A> = {type: "Just", data: A } | {type: "Nothing"}
```

They're called "constructors" because they're functions `Just : a -> Maybe a` that "construct" a "type". Or at least that's how I read all this stuff 🤷

**Comment by lue-bird** [comment]
Correct, union type would be too broad, as elm only has tagged unions.
Constructor (and custom type) feel like too broad terms as well. One is just a function that creates a thing, (the other sounds just like a non-core type)
> variant is the description of a type not it's constructors

Yes and no. elm calls the possible tagged possibilities of a `type` _variants_, see the terms on the [guide](https://guide.elm-lang.org/types/custom_types.html):
> Another benefit of this approach is that each variant can have different associated data

And I like naming the whole thing a variant/choice type as that's what it _is_

**Comment by lue-bird** [comment]
I'm not fixated, though. Custom type is fine, as the official guide calls it that way, too

**Comment by erlandsona** [comment]
Nah re the guide you're super right 😅 ugh that's mildly annoying lol... But totally down to change to Variant & Choice? That's new to but hey I'm down. Yeh change as you see fit. Long as the tests pass should work just fine...

Also if you figure out how to account for the imports that'd be neat too!

**Comment by lue-bird** [comment]
Already implemented in my code-gen-AST version at generate-elm

**Comment by lue-bird** [comment]
Also, I haven't completely looked through the code... But is the prefixing necessary/should it be more configurable?

**Comment by erlandsona** [comment]
By prefixing you mean the `c_` thing, yeh unfortunately... I put a line in the module doc about it. It's unavoidable. Can't use capital letters or _ as the first letter of a function name so "c" for constructor (change it to "v" for variant of you prefer that naming convention) and "_" because Haskell's lens lib uses underscore for prisms like `_Just` & `_Left`... And because the underscore just felt more spacious 😅

**Comment by lue-bird** [comment]
Should prisms be generated for variants with 0 values attached? (I'd say yes, to make checks `is variantErr` easier)

**Comment by lue-bird** [comment]
Also, I will rewrite the rule to generate only prisms that are used – just like `NoMissingRecordFieldLens`

**Comment by lue-bird** [comment]
Also, because we can't generate prisms in `module`s of package dependencies, I will use the hierarchy `Result.Variant.Ok`, creating a separate module for the helpers.
Special case which I might not implement: generate prisms for a `module` internal `type`

**Comment by erlandsona** [comment]
RE: should it (prefix) be more configurable?
Didn't even cross my mind but that's a great idea!

RE: Should prisms be generated for variants with 0 values attached?
Not really a good justification for that I think because lenses/prisms are for accessing nested data... Think of it like trying to access something inside Unit? Does that make sense? If it does I can't really think of a use case for it.

RE: Also, because we can't generate prisms in modules of package dependencies, I will use the hierarchy Result.Variant.Ok, creating a separate module for the helpers.

Personally, I hate how much bloat there is in `import` statements in Elm already...

There's 2 solutions here...
One is update elm-accessors with prisms for all the types in Base. Maybe is already covered but I started working on like JSON? Didn't think to add result but those are a few could be added that way they don't need codegen and they'll get dead code eliminated if they're not used.

Two, personally I'd prefer they get generated into a single leaf file so I can import prisms generated for a custom type for a library (let's say Tree)

At work we codegen all our Lenses into an
`import Gen.Lens as Lens` I wouldn't mind adding a
`import Gen.Prism as Prism`

Tho 🤔

**Comment by lue-bird** [comment]
That's a good idea for package `type`s, it might not be for application types where it leads to `import` cycles and a lot less nice structure.
I also like that prisms are always created locally just like lenses...

What exactly do you dislike so much about longer import sections? I basically never find myself looking at them. Is it because of missing IDE support or someth. else?

**Comment by erlandsona** [comment]
RE: package types, which is what you mentioned when you said Result. I'm assuming stuff in Base is "package" which is why I suggested I'll just write those prisms and expose them from elm-accessors. But for library's that don't already expose prisms for their constructors (well one reason may be that the Constructors are opaque) but otherwise I wouldn't want to pollute the module namespace just for the sake of continuity with the library... It's not that "lot's of imports" bothers me in practice (well it sort of does...) It's that I think most people don't have "code folding" as a basic part of their editor workflow so while sure you can just scroll down past the imports (and I do) it is somewhat annoying that the first thing I see when I open up a >1000 LOC module that the first page of text is just imports 😅

Prisms have to be generated next to the type their operating over because we don't have "extensible variants" like OCaml or ReasonML have. We generate Lenses all in the same module so we can re-use the same "name" lens for a Person, User, Admin, Group, record. Which means our lens file grows sub-linearly with the number of field names in the project (which is great cause it means our codegen never gets that big like it can in C#)

With Prisms there's a much more targeted use case, being like Route Parser or JSON manipulation or something and you can have two sun types with the same constructors in scope in the same module so generating Prisms inline with the type definition is ideal.

**Comment by erlandsona** [comment]
Also just added `ok` & `err` Prisms to elm-accessors.
https://package.elm-lang.org/packages/erlandsona/elm-accessors/latest/Accessors#ok

Not sure if I should name it with the codegen prefix or not given it's mapping to stuff available in elm/core? 🤔

**Comment by lue-bird** [comment]
So your editor doesn't save and restore the view range of a file on exit? Is that a common thing / will that bother many people?

**Comment by lue-bird** [comment]
Also, I wouldn't call it polluting if you put it in sone `source-directories` like `source-generated`.

**Comment by erlandsona** [comment]
> I'd prefix those that aren't implicitly imported (which Result(..) is).
Cool, we're on the same page then. So leaving prefixes off `ok` & `err`.

> So your editor doesn't save and restore the view range of a file on exit?
I use vim, and I'm sure I could configure that but it's not something I've looked into? Should prolly just look into it tho 😅 

> Package.Variant.name route (expect completion of the rule + config + tests etc. in about 3 days)
I don't usually set deadlines / expectations on open source work 😅 

That said, `Package.Variant.name` I still think should just be 
src/Gen/Prism.elm
```elm
module Gen.Prism exposing (c_Variant1_A, c_Variant1_B, c_Variant2_A, c_Variant2_B)

import Package exposing (Type1(Variant1_A, Variant1_B), Type2(Variant2_A, Variant2_B)
```
Then at the call sites instead of
```elm
import Package.Variant1 exposing (c_Variant1_A, c_Variant1_B)
import Package.Variant2 exposing (c_Variant2_A, c_Variant2_B)
```
You'd just have
```elm
import Gen.Lens as Lens
import Gen.Prism as Prism

-- then later you couldj
get (Lens.remoteAddresses << Prism.c_GotData << at 2 << Lens.zip) -- : Maybe Int
```

That's just how I'm seeing things but do what you will 👍

**Comment by lue-bird** [comment]
I think we misunderstood

**Comment by lue-bird** [comment]
And the ~deadline~ time approximation is more about setting expectations :dart:

**Comment by erlandsona** [comment]
And I think regardless, I love what we're doing here so lookin' forward to seein' whatever you come up with! 🤘

**Comment by lue-bird** [comment]
I would change names to
```elm
-RemoteData.Variant.success
+RemoteData.On.success
```
in the spirit of `onEach`. thoughts?
How about `onJust`, `onOk`, `onErr` naming in your package?

**Comment by lue-bird** [comment]
Rule code, readme, ... are now pushed to github. Some bugs still need to be found, tho :)

**Comment by erlandsona** [comment]
I kinda like `on[Variant]` a lot actually... 🤘

**Comment by lue-bird** [comment]
If you have any examples of using those variant prisms in practice, go ahead and add them to the readme through a PR

**Comment by lue-bird** [comment]
Some updates
- dependency `module`s are checked for variant `type`s
- `import` aliases that are recognized as usage, are added on automatic `import`s and can be configured to either
    - the variant origin `module` name `import Data.Extra.Local as Data`
    - the variant origin `module` name with a suffix `import Data.Extra.Local as DataX`
 - custom prism name parsers for names like `onSucceed` → variant `Succeed`

**Pull request merged**
